# Generated by Django 3.2 on 2024-12-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20241201_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttorecipe',
            name='measurement_unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
