# Generated by Django 3.2 on 2024-12-12 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredienttorecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttorecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиентов'),
        ),
    ]
